# Task to automatically build `apple/apple/game-porting-toolkit` 
# and put the resulting Cellar into a dmg

name: Build GPTK
on:
  - workflow_dispatch

jobs:
  build_gptk:
    name: Build GPTK
    strategy:
        matrix:
          flavour: [Vanilla, Vulkan]
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install compiler
        run: |
          brew install apple/apple/game-porting-toolkit-compiler
      - if: matrix.flavour == 'Vulkan'
        name: Patch the formula
        run: |
          patch `brew --repo apple/apple`/Formula/game-porting-toolkit.rb < patches/enable-vulkan-sdl.patch
      - name: Install GPTK
        run: |
          brew install --build-bottle apple/apple/game-porting-toolkit
          rm -rvf `brew --prefix game-porting-toolkit`/include
          rm -rvf `brew --prefix game-porting-toolkit`/INSTALL_RECEIPT.json
          rm -rvf `brew --prefix game-porting-toolkit`/share/man
          find `brew --prefix game-porting-toolkit`/bin -type f ! -name "wine64" ! -name "wine64-preloader" ! -name "wineserver" -exec rm -rf {} +
          tar -zcvf gptk.tar.gz `brew --prefix game-porting-toolkit`
      - name: Upload bottle archive
        uses: actions/upload-artifact@v3
        with:
          name: GTPK ${{matrix.flavour}} brew bottle (Harbor)
          path: gptk.tar.gz
      - name: Capture the Cellar tree (for Whisky)
        run: |
          mkdir gptk-cellar-tree
          cp -r /usr/local/Cellar/game-porting-toolkit/$(ls /usr/local/Cellar/game-porting-toolkit/) gptk-cellar-tree/Wine
          tar -czvf gptk-cellar-tree.tar.gz gptk-cellar-tree
      - name: Upload Cellar tree
        uses: actions/upload-artifact@v3
        with:
          name: GTPK ${{matrix.flavour}} Cellar tree (Whisky)
          path: gptk-cellar-tree.tar.gz

    
