# Task to automatically build `apple/apple/game-porting-toolkit` 
# and put the resulting Cellar into a dmg

name: Build GPTK
on:
  - workflow_dispatch

jobs:
  build_dmg:
    runs-on: macos-13
    steps:
      - name: Install gptk
        run: |
          brew install --build-from-source apple/apple/game-porting-toolkit-compiler
          brew install --build-bottle apple/apple/game-porting-toolkit 
          brew bottle apple/apple/game-porting-toolkit
          mkdir gptk
          cp *.tar.gz gptk
      - name: Create dmg
        run: |
          hdiutil create -volname gptk -srcfolder gptk -ov -format UDZO gptk.dmg
      - name: Upload dmg
        uses: actions/upload-artifact@v2
        with:
          name: gptk
          path: gptk.dmg