# Task to automatically build `apple/apple/game-porting-toolkit` 
# and put the resulting Cellar into a dmg

name: Build GPTK
on:
  - workflow_dispatch

jobs:
  build_dmg:
    runs-on: macos-13
    steps:
      - name: Install gptk
        run: |
          brew install apple/apple/game-porting-toolkit-compiler
          brew install --build-bottle apple/apple/game-porting-toolkit 
          brew bottle apple/apple/game-porting-toolkit
          mkdir gptk
          cp *.tar.gz gptk
      - name: Create bottle archive
        run: |
          tar -czvf gptk.tar.gz gptk
      - name: Upload bottle archive
        uses: actions/upload-artifact@v3
        with:
          name: gptk
          path: gptk.tar.gz
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "gptk.tar.gz"
