# Task to automatically build `apple/apple/game-porting-toolkit` 
# and put the resulting Cellar into a dmg

name: Build GPTK
on:
  - workflow_dispatch

jobs:
  build_gptk:
    strategy:
        matrix:
          flavour: [vanilla, vulkan]
    runs-on: macos-13
    steps:
      - name: Install compiler
        run: |
          brew install apple/apple/game-porting-toolkit-compiler
      - name: Install gptk
        run: |
          brew install --build-bottle apple/apple/game-porting-toolkit 
          brew bottle apple/apple/game-porting-toolkit
          mkdir -p gptk
          mv *.tar.gz gptk
          tar -czvf gptk.tar.gz gptk
          rm -rf gptk
      - if: matrix.flavour == "vulkan"
        name: Patch the formula
        run: |
          patch `brew --repo apple/apple`/Formula/game-porting-toolkit.rb < patches/enable-vulkan-sdl.patch
      - name: Upload bottle archive
        uses: actions/upload-artifact@v3
        with:
          name: GTPK ${{matrix.flavour}} brew bottle (Harbor)
          path: gptk.tar.gz
      - name: Capture the Cellar tree (for Whisky)
        run: |
          mkdir gptk-cellar-tree
          cp -r /usr/local/Cellar/game-porting-toolkit/$(ls /usr/local/Cellar/game-porting-toolkit/) gptk-cellar-tree/Wine
          tar -czvf gptk-cellar-tree.tar.gz gptk-cellar-tree
      - name: Upload Cellar tree
        uses: actions/upload-artifact@v3
        with:
          name: GTPK ${{matrix.flavour}} Cellar tree (Whisky)
          path: gptk-cellar-tree.tar.gz

    
