# Task to automatically build `apple/apple/game-porting-toolkit` 
# and put the resulting Cellar into a dmg

name: Build GPTK
on:
  - workflow_dispatch

jobs:
  build_dmg:
    runs-on: macos-13
    steps:
      - name: Install gptk
        run: |
          brew install --build-from-source apple/apple/game-porting-toolkit apple/apple/game-porting-toolkit-compiler
          brew bottle apple/apple/game-porting-toolkit apple/apple/game-porting-toolkit-compiler
      - name: Create dmg
        run: |
          brew install create-dmg
          # for debugging rn, archive the entire brew Cellar
          create-dmg --volname "gptk" "gptk.dmg" "/usr/local/Cellar/game-porting-toolkit" "/usr/local/Cellar/game-porting-toolkit-compiler"
      - name: Upload dmg
        uses: actions/upload-artifact@v2
        with:
          name: gptk
          path: gptk.dmg