name: Test workflow
on:
  - workflow_dispatch

jobs:
  test:
    runs-on: macos-13
    steps:
      - name: Create folder structure
        run: |
          mkdir -p gptk-cellar-tree/wine
          touch gptk-cellar-tree/wine/i_am_here_to_prevent_git_from_ignoring_this_directory
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Test Cellar tree
          path: gptk-cellar-tree