name: Build GPTK
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 19 * * *"
jobs:
  build_gptk:
    name: Build GPTK
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tap homebrew-apple
        run: brew tap apple/apple http://github.com/apple/homebrew-apple
      - name: Patch GPTK
        run: patch $(brew --repo apple/apple)/Formula/game-porting-toolkit.rb < patches/vulkan.patch
      - name: Patch rpaths
        run: patch $(brew --repo apple/apple)/Formula/game-porting-toolkit.rb < patches/rpath.patch
      - name: Install GPTK
        run: brew install apple/apple/game-porting-toolkit
      - name: Trim Files
        run: |
          rm -rf $(brew --prefix game-porting-toolkit)/.brew
          rm -rf $(brew --prefix game-porting-toolkit)/include
          rm -rf $(brew --prefix game-porting-toolkit)/INSTALL_RECEIPT.json
          rm -rf $(brew --prefix game-porting-toolkit)/share/man
          find $(brew --prefix game-porting-toolkit)/bin -type f -not -name "wine64" -not -name "wine64-preloader" -not -name "wineserver" -delete
          find $(brew --prefix game-porting-toolkit)/bin -type l -delete
      - name: Make Libraries folder
        run: |
          mkdir -p Libraries/Wine
      - name: Copy GPTK
        run: |
          cp -a $(brew --prefix game-porting-toolkit)/. Libraries/Wine/
      - name: Copy external deps
        run: |
          cp -a libs/. Libraries/Wine/lib/
      - name: Copy DXVK
        run: |
          cp -a DXVK Libraries/
      - name: Tar Libraries
        run: |
          tar -zcf Libraries.tar.gz Libraries
      - name: Upload Libraries
        uses: actions/upload-artifact@v3
        with:
          name: Libraries
          path: Libraries.tar.gz
