name: Build GPTK
on:
  - workflow_dispatch
  - push
jobs:
  build_gptk:
    name: Build GPTK
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tap homebrew-apple
        run: brew tap apple/apple http://github.com/apple/homebrew-apple
      - name: Patch GPTK
        run: patch $(brew --repo apple/apple)/Formula/game-porting-toolkit.rb < patches/vulkan.patch
      - name: Patch rpaths
        run: patch $(brew --repo apple/apple)/Formula/game-porting-toolkit.rb < patches/rpath.patch
      - name: Install GPTK
        run: brew -v install apple/apple/game-porting-toolkit
      - name: Trim Files
        run: |
          rm -rvf $(brew --prefix game-porting-toolkit)/.brew
          rm -rvf $(brew --prefix game-porting-toolkit)/include
          rm -rvf $(brew --prefix game-porting-toolkit)/INSTALL_RECEIPT.json
          rm -rvf $(brew --prefix game-porting-toolkit)/share/man
          find $(brew --prefix game-porting-toolkit)/bin -type f -not -name "wine64" -not -name "wine64-preloader" -not -name "wineserver" -delete
          find $(brew --prefix game-porting-toolkit)/bin -type l -delete
      - name: Copy external deps
        run: |
          cp -a libs/. $(brew --prefix game-porting-toolkit)/lib/
      - name: Copy DXVK
        run: |
          cp -r DXVK $(brew --prefix game-porting-toolkit)
      - name: Tar GPTK
        run: |
          tar -zcvf Libraries.tar.gz -C $(brew --prefix game-porting-toolkit) .
      - name: Upload GPTK
        uses: actions/upload-artifact@v3
        with:
          name: Libraries
          path: Libraries.tar.gz
